version: '3.8'

services:
  postgres:
    image: 'postgres:14'
    container_name: 'java-postgres'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=java'
      - 'POSTGRES_PASSWORD=root'